field: 95152ca3-0b9f-4d46-9349-cd429a4e43ea # Blocks
fieldLayouts:
  451f84d0-3114-4310-8e6e-68711bee57b6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 536ad9d9-6bf9-4746-b4ca-a39315a51f69 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1dd1d97d-9fd4-453b-91e9-af70d4d828c5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1d4073da-9b59-4b13-9bb6-a390e2c1a7d4
        userCondition: null
fields:
  536ad9d9-6bf9-4746-b4ca-a39315a51f69: # Text
    columnSuffix: vjurnknn
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      ckeConfig: 1d9bc5dd-4bbd-4783-8a57-3b3078e38657 # Advanced
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: blockText
name: Text
sortOrder: 1
