fieldLayouts:
  20a09ae9-438c-47c2-b441-a5a28ff99401:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 46d273c7-c883-4cf8-b2cb-8cd7a9cdfb92
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 87c31d25-eaea-4be8-b67a-935d2aea4afe # Date
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef53a082-65b9-46ea-a9b7-0df847e6cd4a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e3cc550c-fc28-4ee9-9be6-7ef998d866a9 # Teaser
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a01bfeea-6aec-478c-8526-77c9495f228a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4033c796-d853-4f95-aa8b-4d77d55e9384 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28bc06ee-9826-4615-a0f7-7f3ac84ecf6e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5099f057-fd49-431c-a6fa-ddd239eec776 # News - Category
            instructions: null
            label: Category
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10587462-bcc9-418d-9b79-5b99e4347253
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c4569bc2-0faa-4452-82f9-3344e307871e # Tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 510fa7a2-d078-48f7-b7fe-c5bdcee424f8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 0e61af96-5465-4e62-8753-4ea26a66f1d8
            userCondition: null
          -
            elementCondition: null
            fieldUid: 95152ca3-0b9f-4d46-9349-cd429a4e43ea # Blocks
            instructions: null
            label: Builder
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1143a1b-1916-4e00-b442-a3524062ef60
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f00a0cdb-352c-4205-9542-36d73fbf5661
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8fe74ac6-deb5-488c-ab7b-b527dc0bc970 # Seo - Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd6cee05-d2d4-43e2-9d37-b5bb5b526044
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bd292d9f-94ad-4da3-828b-56cd7c480502 # Seo - Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31093f35-d36b-4917-87b5-dfc2d84ffbfb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6357cf83-498b-401f-8405-7af8e6be8196 # Seo - Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78ad5986-e82b-41fa-8549-41aa6814bae0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e4a7f97-cd35-41d3-bbcc-9278ba3ec9a4 # Seo - Hide
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b91511ee-ea0c-4787-9e4e-2c3f8bb6db96
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: 3a47e296-bebe-4c77-ac7c-6d019f921608
        userCondition: null
handle: newsEntry
hasTitleField: true
name: 'News Entry'
section: 3a7b0cff-9784-4566-82c7-8058d29810aa # News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
