columnSuffix: tewaljhi
contentColumnType: string(640)
fieldGroup: c885c595-cebb-48a3-8d9a-be401441ce25 # Seo
handle: seoDescription
instructions: null
name: 'Seo - Description'
searchable: false
settings:
  byteLimit: null
  charLimit: 160
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
