defaultPlacement: end
enableVersioning: true
handle: categories
name: Categories
propagationMethod: all
siteSettings:
  5a388334-4b50-4126-b1df-67227ce21818: # $SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 04e00e5e-405e-429b-bb73-1f82ea91f65b
type: structure
