defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5a388334-4b50-4126-b1df-67227ce21818: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _entries
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 3
  uid: ff71de62-e842-4926-a071-44014c995b59
type: structure
